name: Hello World Workflow

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
    steps:
      - name: Check Actor
        if: github.actor == 'slecleach'
        run: echo "Hello, World!"

      - name: Deny Unauthorized User
        if: github.actor != 'slecleach'
        run: |
          echo "This workflow can only be run by 'slecleach'."
          exit 1
