name: Hello World Workflow

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-24.04

    steps:
      - name: Check Actor
        if: github.actor == 'alberthli' || github.actor == 'slecleach' || github.actor == 'pulbertson'
        run: echo "Hello, World!"

      - name: Deny Unauthorized User
        if: github.actor != 'alberthli' && github.actor != 'slecleach' && github.actor != 'pulbertson'
        run: |
          echo "This workflow can only be run by 'alberthli', 'slecleach', or 'pulbertson'."
          exit 1
